bootstrap:docker
From:jupyter/scipy-notebook

%post
# Thorin Tabor <tmtabor@cloud.ucsd.edu>
# 8888

USER root
apt-get update && apt-get install -y python-qt4
pip install nbtools genepattern-python genepattern-notebook jupyter-wysiwyg
jupyter nbextension enable --py widgetsnbextension
jupyter nbextension install --py nbtools
jupyter nbextension enable --py nbtools
jupyter serverextension enable --py nbtools
jupyter nbextension install --py genepattern
jupyter nbextension enable --py genepattern
jupyter serverextension enable --py genepattern
jupyter nbextension install --py jupyter_wysiwyg